services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6334:6333"
    volumes:
      - ./qdrant_collections/collections:/qdrant/storage/collections  # монтируем локальную папку коллекций
    environment:
      - QDRANT_HTTP_PORT=6333 
      - QDRANT_GRPC_PORT=6335
    networks:
      - qdrant-network

  fastapi-app:
    build: .
    container_name: fastapi
    ports:
      - "5001:5000"
    volumes:
      - .:/app 
    environment:
      - UV_PROJECT_ENVIRONMENT=/opt/venv
    depends_on:
      - qdrant
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 5000
    networks:
      - qdrant-network

networks:
  qdrant-network:
    driver: bridge
